<a href="https://colab.research.google.com/github/KESHAVNATH8/Machine-Learning-Project/blob/main/Height_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor

In [2]:
df = pd.read_csv('/content/dataset[1].csv')

In [3]:
df

Age  Height
0    10     138
1    11     138
2    12     138
3    13     139
4    14     139
..  ...     ...
66   76     204
67   77     205
68   78     206
69   79     207
70   80     208

[71 rows x 2 columns]

In [4]:
df.head()

Age  Height
0   10     138
1   11     138
2   12     138
3   13     139
4   14     139

In [5]:
df.tail()

Age  Height
66   76     204
67   77     205
68   78     206
69   79     207
70   80     208

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     71 non-null     int64
 1   Height  71 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB


In [7]:
df.describe()

Age      Height
count  71.000000   71.000000
mean   45.000000  160.873239
std    20.639767   20.842902
min    10.000000  138.000000
25%    27.500000  143.500000
50%    45.000000  155.000000
75%    62.500000  171.500000
max    80.000000  208.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     71 non-null     int64
 1   Height  71 non-null     int64
dtypes: int64(2)
memory usage: 1.2 KB


In [11]:
df.isnull().sum()

Age       0
Height    0
dtype: int64

In [42]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [45]:
x

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],
       [77],
       [78],
       [79],
       [80]])

In [46]:
y

array([138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141, 142,
       142, 142, 143, 143, 143, 144, 144, 145, 145, 146, 146, 147, 147,
       148, 148, 149, 149, 150, 150, 151, 152, 153, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 175, 178, 180, 183, 185, 188, 190, 193, 195, 199,
       203, 204, 205, 206, 207, 208])

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [48]:
x_train

array([[53],
       [14],
       [75],
       [60],
       [12],
       [50],
       [21],
       [13],
       [64],
       [55],
       [20],
       [51],
       [59],
       [63],
       [67],
       [42],
       [24],
       [78],
       [29],
       [39],
       [62],
       [45],
       [28],
       [10],
       [25],
       [15],
       [26],
       [30],
       [76],
       [18],
       [23],
       [35],
       [47],
       [27],
       [70],
       [56],
       [73],
       [49],
       [48],
       [11],
       [68],
       [22],
       [71],
       [34],
       [16],
       [33],
       [46],
       [31],
       [19],
       [77],
       [74],
       [57],
       [54]])

In [49]:
y_train

array([163, 139, 203, 169, 138, 160, 141, 139, 173, 164, 141, 161, 168,
       172, 180, 151, 142, 206, 144, 149, 171, 155, 144, 138, 143, 139,
       143, 145, 204, 140, 142, 147, 157, 143, 188, 165, 195, 159, 158,
       138, 183, 142, 190, 147, 140, 146, 156, 145, 141, 205, 199, 166,
       164])

In [50]:
x_test

array([[36],
       [37],
       [58],
       [32],
       [40],
       [61],
       [17],
       [69],
       [44],
       [80],
       [66],
       [38],
       [41],
       [52],
       [43],
       [65],
       [79],
       [72]])

In [51]:
y_test

array([148, 148, 167, 146, 150, 170, 140, 185, 153, 208, 178, 149, 150,
       162, 152, 175, 207, 193])

In [52]:
model = DecisionTreeRegressor()

In [53]:
model.fit(np.array([x_train]).reshape(-1,1), y_train)

DecisionTreeRegressor()

In [56]:
y_pred = model.predict(x_test)

In [57]:
y_pred

array([147., 147., 166., 145., 149., 169., 140., 183., 155., 206., 180.,
       149., 151., 161., 151., 173., 206., 190.])

In [58]:
from sklearn.metrics import r2_score

In [59]:
r2_score(y_test, y_pred)

0.9949220586639661